server:
  port: 8888
  
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/Ambiente_Java/workspace/cursos/alura/microservices_spring_cloud/config-server-microservice/microservice-repo 
